---
title: "Writing Functions"
author: "Molly Martorella"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE, 
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

theme_set(theme_bw())
```


```{r}

x <- rnorm(n = 30, mean = 4, sd = 2.3)
x_again <- rnorm(n = 30, mean = 6, sd = .3)
y <- rnorm(n = 30, mean = 24, sd = 2.3)

(x - mean(x))/sd(x)
(x_again - mean(x_again))/sd(x_again)

# want to automate this.
```

Function:

```{r}

#called z score function, it is an object, the argument is something called x.

z_score <- function(x){
  
  (x - mean(x))/(sd(x))
  
}

```

Try out function:

```{r, error=TRUE}

z_score(x = x_again)

z_score(x = y)

z_score(x = 3)

z_score(x = "my name is Molly")

z_score(x = c(TRUE, TRUE, FALSE, TRUE))

z_score(x = iris)

#function as written requires as object you can compute the mean and sd.

```

update function:

```{r}

z_score <- function(x){
  
  if(!is.numeric(x)){
    stop("x should be numeric")
  } else if (length(x) < 3) {
    stop("x should be longer than 3")
  }
  
  (x - mean(x))/(sd(x))
  
}

```

# Multiple outputs:

```{r}

mean_and_sd <- function(x){
  
  if(!is.numeric(x)){
    stop("x should be numeric")
  } else if (length(x) < 3) {
    stop("x should be longer than 3")
  }
  
  tibble(
    mean_input = mean(x),
    sd = sd(x))

}

```

test:

```{r}

mean_and_sd(x = y)


```


```{r}

mean_and_sd <- function(x){
  
  if(!is.numeric(x)){
    stop("x should be numeric")
  } else if (length(x) < 3) {
    stop("x should be longer than 3")
  }
  
  list(
    mean_input = mean(x),
    sd = sd(x),
    z_score = (x - mean(x))/sd(x))

}


```

test:

```{r}

mean_and_sd(x = y)

```

# Multiple inputs:

```{r}

sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
# use coef to extract linear model coefs (slope and intercept, [1] is intercept, [2] is the slope).

beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]

```

```{r}

sim_regression = function(n) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = 2 + 3 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(n = 30)

#repeatedly running the function gives different estimates every time. Increasing sample size will get closer to slope of 3 and int of 2.

sim_regression(n = 3000)

```


```{r}

sim_regression = function(n, beta0, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(n = 3000, beta0 = 17, beta1 = -3)
sim_regression(n = 30, beta0 = 17, beta1 = -3)

```

```{r}

# can set defaults unless user changes them:

sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(3000)

```

# Scrape napoleon dynamite data:

```{r}
#named url
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

# use rvest package to get all html stuff on the page:
dynamite_html = read_html(url)

# using the selector gadget can get nodes:
review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```

what if want page 2? can change url end to have a 2 instead of a 1, but can write a function to get any page of reviews:

```{r}

read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}

```

```{r}

read_page_reviews("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=6")

```

# Scoping

```{r}

f = function(x) {
  z = x + y
  z
}

x = 1
y = 2

f(x = y)

#produces 4 because, argument is x so wherever x exists in the function it will use what you passed into it. y is a number that is not being passed into the function, so it looks elsewhere for y and will look outside of the function and into environment. 

```


